// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZiCc125zqwblWGLCBdgOiiJYS8UlREA',
    appId: '1:914452705511:web:3eb9677be7c1bb9d477242',
    messagingSenderId: '914452705511',
    projectId: 'ecommerce-app-92532',
    authDomain: 'ecommerce-app-92532.firebaseapp.com',
    storageBucket: 'ecommerce-app-92532.firebasestorage.app',
    measurementId: 'G-LYN6R07PCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNyFsJtS1S531wHgV7FYZrf4jgr84uW8',
    appId: '1:914452705511:android:681f33ad8f17f908477242',
    messagingSenderId: '914452705511',
    projectId: 'ecommerce-app-92532',
    storageBucket: 'ecommerce-app-92532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6cdrjD6-aPoxpZ__yTaX-ZkCvpUNvAqg',
    appId: '1:914452705511:ios:5cb3b61679770049477242',
    messagingSenderId: '914452705511',
    projectId: 'ecommerce-app-92532',
    storageBucket: 'ecommerce-app-92532.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6cdrjD6-aPoxpZ__yTaX-ZkCvpUNvAqg',
    appId: '1:914452705511:ios:5cb3b61679770049477242',
    messagingSenderId: '914452705511',
    projectId: 'ecommerce-app-92532',
    storageBucket: 'ecommerce-app-92532.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwZiCc125zqwblWGLCBdgOiiJYS8UlREA',
    appId: '1:914452705511:web:6936e93812c582fb477242',
    messagingSenderId: '914452705511',
    projectId: 'ecommerce-app-92532',
    authDomain: 'ecommerce-app-92532.firebaseapp.com',
    storageBucket: 'ecommerce-app-92532.firebasestorage.app',
    measurementId: 'G-ZTRBC1S40N',
  );
}
